### ISSUE TITLE
Network lib ?

### ISSUE THREAD

**Issue by rawoke083** [kode4food/ale#11]
HI !
This looks great !
Anyway currently todo any sort of networking, like HTTP, WebSockets, JSON ?

Keep up the good work !

**Comment by kode4food** [comment]
Hi, sorry for taking so long to get back to you. I never got a notification.

There's no way currently to do that with what runtime provides, but you can extend Ale using the [FFI interface](https://www.ale-lang.org/ffi/).

There's a chance I may get back to Ale soon, and this could be one of the things I look at.
