### ISSUE TITLE
Order of object keys changes between calling first and rest

### ISSUE THREAD

**Issue by pstuifzand** [kode4food/ale#5]
The following transcript shows what happens inside `map!`. The functions `first` and `rest` are called on the same object, but depending on the current order of the object it will return the values in different orders, which can result in sometimes getting the same value twice. This is shown in line 262, 263, 268 and 269.

This will also happen in other places where `first` and `rest` are called on the same object.

I read this section in the documentation and could refer to the same situation. If this was intended to apply to this situation, perhaps this could be made more explicit?

> An object can be iterated over as a sequence. The resulting sequence is guaranteed to have no duplicates, but is not guaranteed to return in any particular order.

Transcript:
```
user [255]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [255]= [(:x . 1) ((:y . 2))]
user [256]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [256]= [(:x . 1) ((:y . 2))]
user [257]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [257]= [(:x . 1) ((:y . 2))]
user [258]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [258]= [(:x . 1) ((:y . 2))]
user [259]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [259]= [(:x . 1) ((:y . 2))]
user [260]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [260]= [(:x . 1) ((:y . 2))]
user [261]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [261]= [(:x . 1) ((:y . 2))]
user [262]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [262]= [(:x . 1) ((:x . 1))]
user [263]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [263]= [(:y . 2) ((:y . 2))]
user [264]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [264]= [(:x . 1) ((:y . 2))]
user [265]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [265]= [(:y . 2) ((:x . 1))]
user [266]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [266]= [(:x . 1) ((:y . 2))]
user [267]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [267]= [(:y . 2) ((:x . 1))]
user [268]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [268]= [(:y . 2) ((:y . 2))]
user [269]> (let ([x {:x 1 :y 2}]) [(first x) (rest x)])
     [269]= [(:x . 1) ((:x . 1))]
```

**Comment by kode4food** [comment]
Hi @pstuifzand, thanks for reporting. I originally wanted to snapshot the result of `toSeq()`, but opted not to because of the memory impact. That said, might make sense to do so. Will look into it over the weekend.

**Comment by kode4food** [comment]
Hi @pstuifzand, had a look at it last night. Definitely strange how repeatedly ranging over the keys of an unmodified map would be non-deterministic in Go, but very much seems to be the case.

I've pushed an intermediate solution to master that orders the pairs by the pointer of the keys. It also maintains the (rest) value as an Object. (It had been converted to a list before). 

Let me know if it's working for you.

**Comment by pstuifzand** [comment]
The iteration order is randomized. See the last section in this article. https://blog.golang.org/maps

**Comment by pstuifzand** [comment]
Hi @kode4food, this solves the problem with changing orders of items. Thank you.

**Comment by dc0d** [comment]
@kode4food The `map` type in go seems to be a hash-map (like `hash-map` type in Clojure, which also is not sorted). Maybe it would be more clear to have a separate `sorted-map` type. Since _ale_ will run on Go, maybe this would make more sense.

**Comment by kode4food** [comment]
Hi @dc0d, might make sense, yes. Though I'd have to introduce a comparator protocol of some kind to manage the sorting since the map allows for keys of any value. Will think about a clean way to do this. 

@pstuifzand Glad the change helped. It's far from optimal, but at least you're unblocked

**Comment by kode4food** [comment]
@pstuifzand Shall I call this closed for now?

**Comment by pstuifzand** [comment]
Yeah, no problem.
