### ISSUE TITLE
unrecognized import path "hash/maphash and unrecognized import path "embed" :  import path does not begin with hostname

### ISSUE THREAD

**Issue by alaskacanyon** [kode4food/ale#8]
package hash/maphash: unrecognized import path "hash/maphash" (import path does not begin with hostname)
package embed: unrecognized import path "embed" (import path does not begin with hostname)

**Comment by kode4food** [comment]
Hi @alaskacanyon, can you tell me which version of Go you're using? That package was introduced in 1.14 or 1.15 I believe. Also, Ale requires 1.16 because it is using the new //embed feature.

**Comment by kode4food** [comment]
As the minimum required Go version is represented in the go.mod file, I'm going to close this issue for now.
